export const VIDEOS_DATA = [
  {
    "title": "Hello, this is a test video",
    "thumbnail": "https://netshow.me/wp-content/uploads/2021/10/Como-fazer-uma-thumbnail-1.jpg",
    "desc": "I'm studying and studying so many features to prepare to the future into the IT programming area. Hello World!",
    "views": "4,6 mil visualizações",
    "channelLogo": "https://yt3.ggpht.com/ytc/AIf8zZRpkNLKF0ZFEF6uwMB5pRl_aevaJlVXvMOTvHVF=s68-c-k-c0x00ffffff-no-rj",
    "channelName": "Web Boss",
  },
  {
    "title": "Hello, this is a test video",
    "thumbnail": "https://netshow.me/wp-content/uploads/2021/10/Como-fazer-uma-thumbnail-1.jpg",
    "desc": "I'm studying and studying so many features to prepare to the future into the IT programming area. Hello World!",
    "views": "4,6 mil visualizações",
    "channelLogo": "https://yt3.ggpht.com/ytc/AIf8zZRpkNLKF0ZFEF6uwMB5pRl_aevaJlVXvMOTvHVF=s68-c-k-c0x00ffffff-no-rj",
    "channelName": "Web Boss",
  },
  {
    "title": "Hello, this is a test video",
    "thumbnail": "https://netshow.me/wp-content/uploads/2021/10/Como-fazer-uma-thumbnail-1.jpg",
    "desc": "I'm studying and studying so many features to prepare to the future into the IT programming area. Hello World!",
    "views": "4,6 mil visualizações",
    "channelLogo": "https://yt3.ggpht.com/ytc/AIf8zZRpkNLKF0ZFEF6uwMB5pRl_aevaJlVXvMOTvHVF=s68-c-k-c0x00ffffff-no-rj",
    "channelName": "Web Boss",
  },
  {
    "title": "Hello, this is a test video",
    "thumbnail": "https://netshow.me/wp-content/uploads/2021/10/Como-fazer-uma-thumbnail-1.jpg",
    "desc": "I'm studying and studying so many features to prepare to the future into the IT programming area. Hello World!",
    "views": "4,6 mil visualizações",
    "channelLogo": "https://yt3.ggpht.com/ytc/AIf8zZRpkNLKF0ZFEF6uwMB5pRl_aevaJlVXvMOTvHVF=s68-c-k-c0x00ffffff-no-rj",
    "channelName": "Web Boss",
  },
  {
    "title": "Hello, this is a test video",
    "thumbnail": "https://netshow.me/wp-content/uploads/2021/10/Como-fazer-uma-thumbnail-1.jpg",
    "desc": "I'm studying and studying so many features to prepare to the future into the IT programming area. Hello World!",
    "views": "4,6 mil visualizações",
    "channelLogo": "https://yt3.ggpht.com/ytc/AIf8zZRpkNLKF0ZFEF6uwMB5pRl_aevaJlVXvMOTvHVF=s68-c-k-c0x00ffffff-no-rj",
    "channelName": "Web Boss",
  },
  {
    "title": "Hello, this is a test video",
    "thumbnail": "https://netshow.me/wp-content/uploads/2021/10/Como-fazer-uma-thumbnail-1.jpg",
    "desc": "I'm studying and studying so many features to prepare to the future into the IT programming area. Hello World!",
    "views": "4,6 mil visualizações",
    "channelLogo": "https://yt3.ggpht.com/ytc/AIf8zZRpkNLKF0ZFEF6uwMB5pRl_aevaJlVXvMOTvHVF=s68-c-k-c0x00ffffff-no-rj",
    "channelName": "Web Boss",
  },
  {
    "title": "Hello, this is a test video",
    "thumbnail": "https://netshow.me/wp-content/uploads/2021/10/Como-fazer-uma-thumbnail-1.jpg",
    "desc": "I'm studying and studying so many features to prepare to the future into the IT programming area. Hello World!",
    "views": "4,6 mil visualizações",
    "channelLogo": "https://yt3.ggpht.com/ytc/AIf8zZRpkNLKF0ZFEF6uwMB5pRl_aevaJlVXvMOTvHVF=s68-c-k-c0x00ffffff-no-rj",
    "channelName": "Web Boss",
  },
];
