import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/styles.css"
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Navbar />
        <main className="p-6 sm:p-[5%] w-full flex justify-center items-center">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
